apiVersion: v1
kind: Service
metadata:
  name: oip-webapp-dev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: oip-webapp-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oip-webapp-dev
spec:
  selector:
    matchLabels:
      app: oip-webapp-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: oip-webapp-dev
    spec:
      containers:
      - name: oip-webapp-dev
        image: socialalphaoip/angular-webapp:dev
        ports:
        - containerPort: 80
---

